#Workflow
name: .NET Core CI

#Events
on: 
    push:
    workflow_dispatch: 

jobs:
  greeting:    
    runs-on: ubuntu-latest

    environment: qa

    steps:
      - name: Greeting
        run: echo "${{ vars.REPO }} ${{ vars.HELLO }} ${{ secrets.KEY }}"

  #Job1
  build:
    #Runner
    runs-on: ubuntu-latest

    needs: greeting

    #Steps
    steps:

    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Build
      run: dotnet build --configuration CI

    - name: Test
      run: dotnet test --no-restore --verbosity normal
